### ISSUE TITLE
想要自己打包，发现打不了

### ISSUE THREAD

**Issue by hausen1012** [jaywcjlove/tools#30]
npm run start 也不行
![image](https://user-images.githubusercontent.com/50026605/189057539-31db53ee-79c8-41bb-ba21-d29566f6d16d.png)

**Comment by jaywcjlove** [comment]
@hausen1012 

1. 将渲染端编译出来

https://github.com/jaywcjlove/tools/blob/43d07ded60bcf192167044b5c7d55a813c7fd39a/.github/workflows/ci.yml#L16-L19

2. 编译 app 需要运行

https://github.com/jaywcjlove/tools/blob/43d07ded60bcf192167044b5c7d55a813c7fd39a/.github/workflows/ci.yml#L174-L175

https://github.com/jaywcjlove/tools/blob/43d07ded60bcf192167044b5c7d55a813c7fd39a/.github/workflows/ci.yml#L188

**Comment by hausen1012** [comment]
我看看哈，谢谢
